name: Build and Test Cookbook App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display my SoftUni username
      run: echo "ystefanova"
  
  run-ui-tests:
    needs: build-and-run-unit-tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Run App
      run: npm run start &
    - name: Run UI tests
      run: npm run test:ui

  deploy-to-render:
    needs: run-ui-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
    